jobs:
-
- job: Windows
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo hello from Windows